"""
db/models.py
SQLAlchemy ORM models for the face tracker system.
"""
from datetime import datetime
from sqlalchemy import (
    Column, Integer, String, Float, DateTime, Boolean,
    Text, ForeignKey, LargeBinary, JSON
)
from sqlalchemy.orm import relationship, declarative_base

Base = declarative_base()


class Face(Base):
    """
    Registered face identities.
    Each unique person detected gets one row here.
    """
    __tablename__ = "faces"

    id = Column(Integer, primary_key=True, autoincrement=True)
    face_uuid = Column(String(64), unique=True, nullable=False, index=True)
    first_seen = Column(DateTime, default=datetime.utcnow, nullable=False)
    last_seen = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    visit_count = Column(Integer, default=1)
    embedding = Column(LargeBinary, nullable=False)   # serialised numpy array
    thumbnail_path = Column(String(512))              # path to first-seen crop
    is_watchlist = Column(Boolean, default=False)
    label = Column(String(128))                       # optional human-readable tag
    metadata_ = Column("metadata", JSON, default=dict)

    events = relationship("FaceEvent", back_populates="face", cascade="all, delete-orphan")
    dwell_records = relationship("DwellRecord", back_populates="face", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<Face id={self.id} uuid={self.face_uuid}>"


class FaceEvent(Base):
    """
    Every entry / exit event for every face.
    """
    __tablename__ = "face_events"

    id = Column(Integer, primary_key=True, autoincrement=True)
    face_id = Column(Integer, ForeignKey("faces.id"), nullable=False, index=True)
    face_uuid = Column(String(64), nullable=False, index=True)
    event_type = Column(String(16), nullable=False)   # "entry" | "exit"
    timestamp = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    image_path = Column(String(512))                  # cropped face image on disk
    tracker_id = Column(Integer)                      # DeepSort track ID at time of event
    confidence = Column(Float)
    frame_number = Column(Integer)
    bbox = Column(JSON)                               # {"x1": , "y1": , "x2": , "y2": }

    face = relationship("Face", back_populates="events")

    def __repr__(self):
        return f"<FaceEvent id={self.id} type={self.event_type} face={self.face_uuid}>"


class DwellRecord(Base):
    """
    Tracks how long a face was visible (entry → exit pair).
    """
    __tablename__ = "dwell_records"

    id = Column(Integer, primary_key=True, autoincrement=True)
    face_id = Column(Integer, ForeignKey("faces.id"), nullable=False, index=True)
    face_uuid = Column(String(64), nullable=False)
    entry_time = Column(DateTime, nullable=False)
    exit_time = Column(DateTime)
    dwell_seconds = Column(Float)
    session_number = Column(Integer, default=1)       # how many times this person visited

    face = relationship("Face", back_populates="dwell_records")


class SystemAlert(Base):
    """
    Alerts generated by the system (crowd threshold, loitering, watchlist hits).
    """
    __tablename__ = "system_alerts"

    id = Column(Integer, primary_key=True, autoincrement=True)
    alert_type = Column(String(64), nullable=False)   # "crowd_threshold" | "loitering" | "watchlist"
    severity = Column(String(16), default="info")     # "info" | "warning" | "critical"
    message = Column(Text)
    timestamp = Column(DateTime, default=datetime.utcnow)
    face_uuid = Column(String(64))
    extra = Column(JSON, default=dict)
    acknowledged = Column(Boolean, default=False)


class VisitorStats(Base):
    """
    Hourly aggregated stats — used for the dashboard charts.
    """
    __tablename__ = "visitor_stats"

    id = Column(Integer, primary_key=True, autoincrement=True)
    hour_bucket = Column(DateTime, nullable=False, index=True, unique=True)
    unique_visitors = Column(Integer, default=0)
    total_entries = Column(Integer, default=0)
    total_exits = Column(Integer, default=0)
    avg_dwell_seconds = Column(Float)
    peak_concurrent = Column(Integer, default=0)
